site_name: Estruturas de Dados e Algoritmos
copyright: 2022 Nicolas Souza
repo_name: EDA2-notes
repo_url: https://github.com/nszchagas/EDA2-notes

theme:
  name: material
  logo: _static/icon.png
  features:
    - content.code.annotate
    - content.code.copy
  favicon: _static/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["codes"]
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - Endereços e Ponteiros: resumos/ponteiros.md
  - Listas Encadeadas:
      - Resumo: resumos/listas_encadeadas.md
      - Implementação: implementacao/listas_encadeadas.md
  - Ordenação:
      - Seleção: ordenacao/selecao.md
      - Mergesort: ordenacao/mergesort.md
      - Quicksort: ordenacao/quicksort.md
  - Hash: resumos/hash.md
  - Árvores Binárias: resumos/arvores_binarias.md
  - Árvores Binárias de Busca: resumos/arvore_binaria_busca.md
  - Fila de prioridade: resumos/fila_de_prioridade.md
  - Heap: resumos/heap.md
  - Grafos:
      - Estrutura: resumos/grafos/estrutura.md
      - Percursos: resumos/grafos/percursos.md
      - Algoritmos: resumos/grafos/algoritmos.md
