site_name: Estruturas de Dados e Algoritmos
copyright: 2022 Nicolas Souza
repo_name: EDA2-notes
repo_url: https://github.com/nszchagas/EDA2-notes

theme:
  name: material
  logo: _static/icon.png
  features:
    - content.code.annotate
  favicon: _static/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - Estruturas:
      - Endereços e Ponteiros: ponteiros.md
      - Listas Encadeadas: listas_encadeadas.md
      - Árvores: arvores.md
  - Ordenação:
      - Seleção: ordenacao/selecao.md
      - Mergesort: ordenacao/mergesort.md
      - Quicksort: ordenacao/quicksort.md
  - Implementação:
      - Listas encadeadas: implementacao/listas_encadeadas.md
